### ISSUE TITLE
Published alpha versions in drafts are not public and hence cannot be downloaded

### ISSUE THREAD

**Issue by pravindahal** [coopnorge/helm-base-chart#59]
Work around is to download the artifact and store it in the charts dir in the helm chart. 

- [x] Implement the workflow to publish releases to oci
- [x] Make sure renovatebot works

**Comment by AtzeDeVries** [comment]
Potential workarounds are

* Artifact registry
* Store the artefacts in a public gcp bucket

**Comment by pravindahal** [comment]
I was trying to add infra code here: https://github.com/coopnorge/helm-base-chart/pull/93 but I just realized that this is a public repo. Should the infra code be added to a separate private repo for this?

**Comment by pravindahal** [comment]
Renovatebot works: https://github.com/coopnorge/pravindahal-project/pull/299

**Comment by pravindahal** [comment]
Next steps:
- https://github.com/coopnorge/helm-base-chart/issues/104
- https://github.com/coopnorge/helm-base-chart/issues/102
